import Link from 'next/link';
import { Logo } from '@/components/brand/logo';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Disclaimer — SYNLUMEX INTEL',
  description: 'Important disclaimers regarding the use of SYNLUMEX INTEL.'
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-40 h-16 border-b border-border bg-background/80 backdrop-blur-lg">
        <div className="max-w-7xl mx-auto h-full px-6 flex items-center justify-between">
          <Link href="/" className="group flex items-center">
            <Logo size={28} interactive />
          </Link>
          <Link
            href="/"
            className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-2"
          >
            <ArrowLeft className="h-3.5 w-3.5" /> Back to home
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="text-xs font-mono tracking-widest text-brand-cyan uppercase mb-3">
          LEGAL
        </div>
        <h1 className="text-3xl md:text-4xl font-semibold tracking-[-0.03em] mb-2">
          Disclaimer
        </h1>
        <p className="text-sm text-muted-foreground font-mono mb-12">
          Last updated: 22 September 2026
        </p>

        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              1. General information
            </h2>
            <p>
              SYNLUMEX INTEL is a software platform. Information presented on this website and
              inside the platform is for general informational purposes only. It does not
              constitute professional, financial, legal, or construction advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              2. AI-generated output
            </h2>
            <p>
              AI-powered features (including but not limited to BOQ extraction, risk analysis, and
              Intel AI chat) generate automated output. This output:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Is generated by third-party large language models</li>
              <li>May contain errors, omissions, or inaccuracies</li>
              <li>Is intended as a starting point for human review, not a final decision</li>
              <li>
                Should not be relied upon for financial, contractual, safety-critical, or legally
                binding decisions without independent verification
              </li>
            </ul>
            <p className="mt-3">
              SYNLUMEX does not guarantee the accuracy, completeness, or fitness for any purpose
              of AI-generated output.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              3. No professional advice
            </h2>
            <p>
              Nothing in SYNLUMEX INTEL or on this website should be construed as professional
              advice of any kind. You should consult qualified professionals (engineers, CPAs,
              lawyers, or other licensed advisors) for advice specific to your situation.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              4. Third-party references
            </h2>
            <p>
              References to third-party companies (Procore, Autodesk, Oracle, SAP, and others) are
              for comparative and informational purposes only. SYNLUMEX is not affiliated with,
              endorsed by, or sponsored by any of these companies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              5. External links
            </h2>
            <p>
              This website may contain links to external sites. SYNLUMEX does not control or
              endorse the content of any external site and is not responsible for their content,
              privacy practices, or availability.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              6. Availability
            </h2>
            <p>
              We aim for high availability but do not guarantee uninterrupted or error-free
              service. Planned and unplanned maintenance may cause temporary downtime.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              7. Limitation of liability
            </h2>
            <p>
              To the maximum extent permitted by law, SYNLUMEX is not liable for any indirect,
              incidental, consequential, or punitive damages arising from the use of the platform
              or reliance on information provided on this website.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">
              8. Contact
            </h2>
            <p>
              Questions?{' '}
              <a href="mailto:abdul@synlumexai.com" className="text-brand-cyan hover:underline">
                abdul@synlumexai.com
              </a>{' '}
              · WhatsApp +91 93907 85041
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-border flex flex-wrap items-center gap-4 text-xs text-muted-foreground font-mono">
          <Link href="/" className="hover:text-foreground">Home</Link>
          <Link href="/privacy" className="hover:text-foreground">Privacy</Link>
          <Link href="/terms" className="hover:text-foreground">Terms</Link>
          <Link href="/refund" className="hover:text-foreground">Refund</Link>
          <Link href="/about" className="hover:text-foreground">About</Link>
          <Link href="/contact" className="hover:text-foreground">Contact</Link>
        </div>
      </div>
    </div>
  );
}
